<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * m_closure_reason arrived from MySQL with its `id` column but without its key:
 * no primary key and no sequence. Two consequences:
 *   1. Postgres refuses any foreign key aimed at it — an FK target must be provably unique.
 *   2. INSERT INTO m_closure_reason (reason) fails — id is NOT NULL with no default.
 * Both are repaired here so account_closure can safely reference this table.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('m_closure_reason', function (Blueprint $table) {
            $table->primary('id');   // alter table ... add primary key ("id")
        });

        // Give id a generator again. BY DEFAULT (not ALWAYS) so a seeder may still
        // supply an explicit id when it needs to.
        DB::statement('ALTER TABLE m_closure_reason ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');

        // Point the counter past the rows that already exist (1 and 2), or the next
        // insert would try id = 1 and collide with the primary key we just added.
        // Third argument false = "not yet used", so an empty table would start at 1.
        DB::statement("
            SELECT setval(
                pg_get_serial_sequence('m_closure_reason', 'id'),
                COALESCE(MAX(id), 1),
                MAX(id) IS NOT NULL
            ) FROM m_closure_reason
        ");
    }

    public function down(): void
    {
        DB::statement('ALTER TABLE m_closure_reason ALTER COLUMN id DROP IDENTITY IF EXISTS');

        Schema::table('m_closure_reason', function (Blueprint $table) {
            $table->dropPrimary();   // Postgres names it m_closure_reason_pkey
        });
    }
};
