<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Master list of DDOs (Drawing & Disbursing Officers) — maps onto `ddo_master`.
 *
 * A DDO now belongs to a TREASURY (`treasury_code`). It also still carries the legacy
 * `loc_code` (varchar) so the old DDO→Location data is preserved; the screen just shows
 * Treasury instead. Both relationships live here.
 *
 * Legacy quirk on `loc_code`: it is varchar(10) while `loc_master.loc_code` is bigint —
 * numeric values that Postgres coerces; we cast to string when filtering. `treasury_code`
 * has no such mismatch: both sides are varchar(10).
 *
 * Phase A: `ddo_code` is AUTO-GENERATED by the database sequence (in sync with the
 * data), no timestamps.
 */
class Ddo extends Model
{
    protected $table = 'ddo_master';

    protected $primaryKey = 'ddo_code';

    /** Auto-generated by the ddo_master sequence (admin never types it). */
    public $incrementing = true;

    protected $keyType = 'int';

    public $timestamps = false;

    protected $fillable = ['ddo_code', 'ddo_name', 'loc_code', 'treasury_code'];

    /** The treasury this DDO belongs to (the current link). */
    public function treasury(): BelongsTo
    {
        return $this->belongsTo(Treasury::class, 'treasury_code', 'treasury_code');
    }

    /** The location this DDO used to belong to — retained legacy data. */
    public function location(): BelongsTo
    {
        return $this->belongsTo(Location::class, 'loc_code', 'loc_code');
    }

    /**
     * Filter DDOs by the cascading treasury filter — shared by the list and the Excel
     * export so they always agree.
     *  - a specific treasury wins,
     *  - else a district narrows to that district's treasuries,
     *  - else no filter.
     *
     * No casting needed here: treasury_code is varchar on both ddo_master and treasury_master.
     */
    public function scopeForTreasuryFilter(Builder $query, string $distCode, string $treasuryCode): Builder
    {
        if ($treasuryCode !== '') {
            return $query->where('treasury_code', $treasuryCode);
        }

        if ($distCode !== '') {
            $codes = Treasury::query()->where('dist_code', $distCode)->pluck('treasury_code');

            return $query->whereIn('treasury_code', $codes);
        }

        return $query;
    }

    /**
     * Filter DDOs by the cascading location filter — shared by the list and the
     * Excel export so they always agree.
     *  - a specific location wins,
     *  - else a district narrows to that district's locations,
     *  - else no filter.
     */
    public function scopeForLocationFilter(Builder $query, string $distCode, string $locCode): Builder
    {
        if ($locCode !== '') {
            return $query->where('loc_code', $locCode);   // varchar = string
        }

        if ($distCode !== '') {
            // loc_master.loc_code is bigint; cast to string to match the varchar column.
            $codes = Location::query()->where('dist_code', $distCode)
                ->pluck('loc_code')->map(fn ($v) => (string) $v);

            return $query->whereIn('loc_code', $codes);
        }

        return $query;
    }

    /** Case-insensitive search over code + name (kept for reuse; not currently wired). */
    public function scopeSearch(Builder $query, ?string $term): Builder
    {
        $term = trim((string) $term);

        if ($term === '') {
            return $query;
        }

        return $query->where(function (Builder $q) use ($term) {
            $q->whereRaw('LOWER(ddo_name) LIKE ?', ['%'.strtolower($term).'%'])
                ->orWhereRaw('CAST(ddo_code AS TEXT) LIKE ?', ['%'.$term.'%']);
        });
    }
}
