<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Master list of designations — maps onto the legacy `designation_master` table.
 *
 * Unlike the other masters, `designation_id` is a purely-internal counter (nobody
 * types "designation #1870"), so we let the database AUTO-GENERATE it. The Postgres
 * table already has a sequence for this column and it is in sync with the data.
 */
class Designation extends Model
{
    protected $table = 'designation_master';

    protected $primaryKey = 'designation_id';

    /** Auto-generated by the database sequence (the exception among the masters). */
    public $incrementing = true;

    protected $keyType = 'int';

    public $timestamps = false;

    protected $fillable = ['designation'];

    /** Case-insensitive search over id + name (works on Postgres and SQLite). */
    public function scopeSearch(Builder $query, ?string $term): Builder
    {
        $term = trim((string) $term);

        if ($term === '') {
            return $query;
        }

        return $query->where(function (Builder $q) use ($term) {
            $q->whereRaw('LOWER(designation) LIKE ?', ['%'.strtolower($term).'%'])
                ->orWhereRaw('CAST(designation_id AS TEXT) LIKE ?', ['%'.$term.'%']);
        });
    }
}
