<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Master list of districts — maps onto the legacy `dist_master` table.
 *
 * Phase A (compatibility-first): we point Eloquent at the existing table with no
 * schema changes.
 *  - `dist_code` is a hand-assigned numeric code (an admin types it), so it is
 *    NOT auto-incrementing.
 *  - the legacy table has no created_at / updated_at columns.
 *
 * A district is the root of the District → Location → DDO chain; the delete guard
 * that protects that chain lives in the Districts Livewire component for now and
 * becomes a proper `locations()` relationship once the Location model exists (3d).
 */
class District extends Model
{
    protected $table = 'dist_master';

    protected $primaryKey = 'dist_code';

    /** The code is entered by an admin, not generated by the database. */
    public $incrementing = false;

    /** `dist_code` is a bigint. */
    protected $keyType = 'int';

    /** Legacy table has no timestamp columns. */
    public $timestamps = false;

    protected $fillable = ['dist_code', 'state_code', 'dist_name'];

    /** The locations that belong to this district (the delete guard uses this). */
    public function locations(): HasMany
    {
        return $this->hasMany(Location::class, 'dist_code', 'dist_code');
    }

    /**
     * The state this district belongs to.
     *
     * Nullable in the DB: the 30 legacy districts start with no state and get one the
     * first time an admin edits them. `?->state_name` in the view handles the NULLs.
     */
    public function state(): BelongsTo
    {
        return $this->belongsTo(State::class, 'state_code', 'state_code');
    }

    /**
     * Case-insensitive search over code + name, shared by the list screen and the
     * Excel export so they always filter identically.
     *
     * `LOWER(col) LIKE` keeps it case-insensitive on BOTH Postgres (prod) and
     * SQLite (tests) — unlike Postgres-only `ILIKE`.
     */
    public function scopeSearch(Builder $query, ?string $term): Builder
    {
        $term = trim((string) $term);

        if ($term === '') {
            return $query;
        }

        return $query->where(function (Builder $q) use ($term) {
            $q->whereRaw('LOWER(dist_name) LIKE ?', ['%'.strtolower($term).'%'])
                ->orWhereRaw('CAST(dist_code AS TEXT) LIKE ?', ['%'.$term.'%']);
        });
    }
}
