<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Master list of states / union territories — maps onto our own `state_master` table.
 *
 *  - `state_code` is the official LGD code (hand-known), so it is NOT auto-incrementing.
 *  - Static reference data, so no created_at / updated_at columns (like the other masters).
 */
class State extends Model
{
    protected $table = 'state_master';

    protected $primaryKey = 'state_code';

    /** The code is the real LGD number, not generated by the database. */
    public $incrementing = false;

    protected $keyType = 'int';

    public $timestamps = false;

    protected $fillable = ['state_code', 'state_name'];

    /** The districts that belong to this state. */
    public function districts(): HasMany
    {
        return $this->hasMany(District::class, 'state_code', 'state_code');
    }
}
